logging:
  LOGGER_NAME: 'root'

fetch_data:
  indices:
    start: 50000
    end: 62000
  save_location: "Data/raw/"

clean_data:
  save_location: "Data/clean/"

create_corpus:
  save_location: "Data/processed/"
